sudo: required
dist: trusty

language: python
python:
    - "3.3"
    - "3.4"
    - "3.5"
    - "3.6"

services:
  - redis-server
env:
    - REDIS=localhost

install:
    - pip install .
    - pip install -r requirements-dev.txt
script: py.test
